# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-10 22:58
from __future__ import unicode_literals

import ckeditor.fields
import ckeditor_uploader.fields
import ctstem_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctstem_app', '0180_auto_20191220_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentinstance',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('P', 'In Progress'), ('S', 'Submitted'), ('F', 'Feedback Ready'), ('A', 'Archived')], default='N', max_length=255),
        ),
        migrations.AlterField(
            model_name='assignmentinstance',
            name='teammates',
            field=models.ManyToManyField(blank=True, help_text='On Windows use Ctrl+Click to make multiple selection.  On a Mac use Cmd+Click to make multiple selection', null=True, to='ctstem_app.Student'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='teacher_only',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, help_text='Upload an image at least 400x289 in resolution that represents this category', null=True, upload_to=ctstem_app.models.upload_file_to),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='acknowledgement',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Resources, models, and other material used in this curriculum; past authors/contributors', null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='authors',
            field=models.ManyToManyField(help_text='Select authors for this curriculum', related_name='curriculum_authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='compatible_system',
            field=models.ManyToManyField(blank=True, help_text='Select one or more compatible systems', null=True, to='ctstem_app.System'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='credits',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Author contributions', null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='feature_rank',
            field=models.IntegerField(blank=True, help_text='Order in the feature pool', null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='icon',
            field=models.ImageField(blank=True, help_text='Upload an image at least 400x289 in resolution that represents this curriculum', null=True, upload_to=ctstem_app.models.upload_file_to),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='level',
            field=models.TextField(blank=True, help_text='(ex. high school AP or Advanced Physics course)', null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='order',
            field=models.IntegerField(blank=True, help_text='Order within the Unit', null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='overview',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Description of the curriculum; This text is shown to teachers and researchers only', null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='purpose',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Purpose of this curriculum', null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Select teachers to share this curriculum with before it is public', null=True, to='ctstem_app.Teacher'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='status',
            field=models.CharField(choices=[('D', 'Private'), ('P', 'Public'), ('A', 'Archived'), ('R', 'Deleted')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='student_overview',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Description of what students will learn in this curriculum; This text is shown to students only', null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='subject',
            field=models.ManyToManyField(blank=True, help_text='Select one or more subjects', null=True, to='ctstem_app.Subject'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='time',
            field=models.CharField(blank=True, help_text='Estimated time students would spend on this curriculum (ex. 7-9 class periods of 45-50 minutes)', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='title',
            field=models.CharField(help_text='Name of Unit or Lesson', max_length=256),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Select a unit if this curriculum is part of one', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='underlying_curriculum', to='ctstem_app.Curriculum'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=ckeditor.fields.RichTextField(default='Enter publication', help_text='Enter publication details'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_field_type',
            field=models.CharField(choices=[('TA', 'Text Area'), ('TF', 'Text Field'), ('DD', 'Drop Down'), ('MS', 'Multi-Select'), ('MC', 'Multiple Choice'), ('MI', 'Multiple Choice w/ Images'), ('MH', 'Multiple Choice w/ Horizontal Layout'), ('FI', 'File'), ('SK', 'Sketch'), ('DT', 'Data Table')], default='TF', max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.TextField(blank=True, help_text='Click on the &#9432; icon to see the Options Guide', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='sketch_background',
            field=models.ImageField(blank=True, help_text='Upload a background image at least 900x500 in resolution for the sketch pad', null=True, upload_to=ctstem_app.models.upload_file_to),
        ),
        migrations.AlterField(
            model_name='questionfeedback',
            name='feedback',
            field=models.TextField(blank=True, help_text='Enter Feedback', null=True),
        ),
        migrations.AlterField(
            model_name='questionresponsefile',
            name='file',
            field=models.FileField(help_text='Upload a file less than 5 MB in size.', upload_to=ctstem_app.models.upload_file_to),
        ),
        migrations.AlterField(
            model_name='schooladministrator',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ctstem_app.School'),
        ),
        migrations.AlterField(
            model_name='step',
            name='title',
            field=models.CharField(blank=True, help_text='Page title', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='consent',
            field=models.CharField(choices=[('A', 'I Agree'), ('D', 'I Disagree')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='parental_consent',
            field=models.CharField(choices=[('U', 'Unknown'), ('A', 'Agree'), ('D', 'Disagree')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ctstem_app.School'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='icon',
            field=models.ImageField(blank=True, help_text='Upload an image at least 400x289 in resolution that represents this subject', null=True, upload_to=ctstem_app.models.upload_file_to),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='consent',
            field=models.CharField(choices=[('A', 'I Agree'), ('D', 'I Disagree')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='ctstem_app.School'),
        ),
        migrations.AlterField(
            model_name='team',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='ctstem_app.TeamRole'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='email',
            field=models.EmailField(help_text='Email', max_length=255),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='name',
            field=models.CharField(help_text='Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='school',
            field=models.CharField(help_text='School Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='subject',
            field=models.CharField(help_text='Subject', max_length=255),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='icon',
            field=models.ImageField(blank=True, help_text='Upload an image at least 400x289 in resolution that represents this class', null=True, upload_to=ctstem_app.models.upload_file_to),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Select teachers to share this class with.', null=True, to='ctstem_app.Teacher'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='ctstem_app.Teacher'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='title',
            field=models.CharField(help_text='Class Title. Eg. Physics Section A', max_length=50),
        ),
    ]
