# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-10 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctstem_app', '0181_auto_20191210_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentinstance',
            name='teammates',
            field=models.ManyToManyField(blank=True, help_text='On Windows use Ctrl+Click to make multiple selection.  On a Mac use Cmd+Click to make multiple selection', to='ctstem_app.Student'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='compatible_system',
            field=models.ManyToManyField(blank=True, help_text='Select one or more compatible systems', to='ctstem_app.System'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Select teachers to share this curriculum with before it is public', to='ctstem_app.Teacher'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='subject',
            field=models.ManyToManyField(blank=True, help_text='Select one or more subjects', to='ctstem_app.Subject'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='taxonomy',
            field=models.ManyToManyField(blank=True, to='ctstem_app.Subcategory'),
        ),
        migrations.AlterField(
            model_name='question',
            name='research_category',
            field=models.ManyToManyField(blank=True, related_name='questions', to='ctstem_app.ResearchCategory'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_of', through='ctstem_app.Membership', to='ctstem_app.Student'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Select teachers to share this class with.', to='ctstem_app.Teacher'),
        ),
    ]
