# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-03 17:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ctstem_app', '0182_auto_20191210_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, help_text='Curriculum Author Order', null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctstem_app.Curriculum')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='curriculumauthor',
            unique_together=set([('curriculum', 'author')]),
        ),
    ]
