# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-03 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctstem_app', '0183_add_table_curriculum_author'),
    ]

    operations = [
      migrations.RunSQL('INSERT INTO ctstem_app_curriculumauthor(curriculum_id, author_id, "order") SELECT curriculum_id, user_id, 1 FROM ctstem_app_curriculum_authors;'),

    ]
