# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-05 22:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctstem_app', '0184_migrate_curriculum_authors_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='authors',
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='locked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_locked_curriculum', to=settings.AUTH_USER_MODEL),
        ),
    ]
