# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-05 22:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ctstem_app', '0185_auto_20200205_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='authors',
            field=models.ManyToManyField(through='ctstem_app.CurriculumAuthor', to=settings.AUTH_USER_MODEL),
        ),
    ]
