# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-10 15:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ctstem_app', '0186_curriculum_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumCollaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, help_text='Curriculum Order for Authors', null=True)),
                ('privilege', models.CharField(choices=[('V', 'View'), ('E', 'Edit')], max_length=1)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctstem_app.Curriculum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='curriculum',
            name='collaborators',
            field=models.ManyToManyField(related_name='collaborated_curricula', through='ctstem_app.CurriculumCollaborator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='curriculumcollaborator',
            unique_together=set([('curriculum', 'user')]),
        ),
    ]
