# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-10 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctstem_app', '0187_auto_20200410_1031'),
    ]

    operations = [
      migrations.RunSQL('INSERT INTO ctstem_app_curriculumcollaborator(curriculum_id, user_id, privilege, "order") \
                            SELECT curriculum_id, author_id, \'E\', "order" \
                            FROM ctstem_app_curriculumauthor;'),

      migrations.RunSQL('INSERT INTO ctstem_app_curriculumcollaborator(curriculum_id, user_id, privilege) \
                              SELECT s.curriculum_id, t.user_id, \'V\' \
                              FROM ctstem_app_curriculum_shared_with s JOIN ctstem_app_teacher t on s.teacher_id = t.id \
                              WHERE NOT EXISTS(SELECT 1 \
                                               FROM ctstem_app_curriculumauthor a \
                                               WHERE a.author_id = t.user_id);'),
    ]
