# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-27 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctstem_app', '0188_migrate_authors_and_shared_with_to_collaborators'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curriculumauthor',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='curriculumauthor',
            name='author',
        ),
        migrations.RemoveField(
            model_name='curriculumauthor',
            name='curriculum',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='shared_with',
        ),
        migrations.DeleteModel(
            name='CurriculumAuthor',
        ),
    ]
