# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-28 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctstem_app', '0189_auto_20200427_1358'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set([('curriculum', 'group')]),
        ),
    ]
