# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-18 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctstem_app', '0191_migrate_underlying_lessons_collaborators_to_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='curriculum_type',
            field=models.CharField(choices=[('U', 'Unit'), ('L', 'Lesson'), ('A', 'Assessment')], max_length=1),
        ),
    ]
