# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-23 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctstem_app', '0192_auto_20200618_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='locked_by',
        ),
    ]
