# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-08 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctstem_app', '0193_remove_curriculum_locked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='teacher_notes',
        ),
    ]
