# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-03 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctstem_app', '0194_remove_step_teacher_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='curriculum_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
