# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-04 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctstem_app', '0195_curriculum_curriculum_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='curriculum_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
