# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-11 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctstem_app', '0196_auto_20200804_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchcategory',
            name='abbrevation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='researchcategory',
            name='flag',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False),
        ),
    ]
