# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-15 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctstem_app', '0199_question_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='created',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='question',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
