# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-29 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctstem_app', '0200_auto_20200915_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='visibility',
            field=models.CharField(choices=[('D', 'Private'), ('P', 'Public')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='assignmentinstance',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('P', 'In Progress'), ('S', 'Submitted'), ('F', 'Feedback Completed'), ('A', 'Archived')], default='N', max_length=255),
        ),
    ]
