# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-29 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctstem_app', '0202_question_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copied_questions', to='ctstem_app.Question'),
        ),
    ]
