# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-09 18:03
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctstem_app', '0204_question_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Version Number', max_length=255)),
                ('release_date', models.DateField()),
                ('release_type', models.CharField(choices=[('B', 'Bug Fixes'), ('A', 'Major Changes'), ('I', 'Minor Changes')], max_length=1)),
                ('release_note', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
