# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-09 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctstem_app', '0205_releasenote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('B', 'Bug Fixes'), ('A', 'Major Changes'), ('I', 'Minor Changes')], max_length=1)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='releasenote',
            name='release_note',
        ),
        migrations.RemoveField(
            model_name='releasenote',
            name='release_type',
        ),
        migrations.AlterField(
            model_name='releasenote',
            name='version',
            field=models.CharField(help_text='Format: 3.2.1', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='releasechange',
            name='release_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='ctstem_app.ReleaseNote'),
        ),
    ]
