# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-01 15:39
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctstem_app', '0208_auto_20210215_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('order', models.IntegerField()),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('order', models.IntegerField()),
                ('topic_type', models.CharField(choices=[('U', 'User Guide'), ('H', 'Help and FAQ')], max_length=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='userguidesubtopic',
            name='topic',
        ),
        migrations.DeleteModel(
            name='UserGuideSubTopic',
        ),
        migrations.DeleteModel(
            name='UserGuideTopic',
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='ctstem_app.Topic'),
        ),
    ]
