# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-05 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctstem_app', '0209_auto_20210301_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentfeedback',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctstem_app.AssignmentInstance', unique=True),
        ),
    ]
