# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-29 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctstem_app', '0211_auto_20210308_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='test_account',
            field=models.BooleanField(default=False),
        ),
    ]
