# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-16 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctstem_app', '0212_student_test_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='realtime_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
