# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-17 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctstem_app', '0213_assignment_realtime_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='anonymize_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Select teachers to share this class with.', related_name='shared_groups', to='ctstem_app.Teacher'),
        ),
    ]
