# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-19 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctstem_app', '0214_auto_20210622_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='anonymize_student',
            field=models.BooleanField(default=False),
        ),

    ]
