# Generated by Django 2.2.25 on 2022-01-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctstem_app', '0215_auto_20210719_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.CharField(default='abc', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='publisher',
            field=models.CharField(default='abc', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='tag',
            field=models.CharField(choices=[('01', 'Teachers'), ('02', 'Students'), ('03', 'Methodology'), ('04', 'CT-Integration')], default='01', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='title',
            field=models.CharField(default='abc', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='year',
            field=models.IntegerField(default=2018),
            preserve_default=False,
        ),
    ]
