# Generated by Django 2.2.25 on 2022-01-24 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctstem_app', '0216_auto_20220124_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['tag', 'year', 'authors']},
        ),
        migrations.RemoveField(
            model_name='publication',
            name='order',
        ),
    ]
