# Generated by Django 2.2.25 on 2022-02-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctstem_app', '0217_auto_20220124_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='tag',
            field=models.CharField(choices=[('01', 'CT-Integration'), ('02', 'Teachers'), ('03', 'Students'), ('04', 'Methodology')], max_length=2),
        ),
    ]
