# Generated by Django 2.2.27 on 2022-02-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctstem_app', '0218_auto_20220211_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='pages',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='volume',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(help_text='Enter comma separated list of authors: Last name, First initial.,', max_length=512),
        ),
        migrations.AlterField(
            model_name='publication',
            name='web_link',
            field=models.URLField(blank=True, help_text='Start with http:// or https://', null=True),
        ),
    ]
